export type AdapterBoundary = 'sanitized-ingress' | 'capability-profile';

export {
  categorizeBuiltinTool,
  categorizeBuiltInTool,
  categorizeTool,
  canonicalToolName,
  canonicalToolNameForCategory,
  isMcpToolName,
  MCP_TOOL_CATEGORY,
  TOOL_INPUT_PROPERTY_KEYS,
  toolCategories,
  UNKNOWN_TOOL_CATEGORY,
} from './tool-category.js';
export type { CanonicalToolName } from './tool-category.js';

export {
  buildAgentFinishedPayload,
  buildAgentSpawnedPayload,
  buildAgentStateChangedPayload,
  buildPermissionPayload,
  buildPermissionRequestedPayload,
  buildPermissionResolvedPayload,
  buildSessionEndedPayload,
  buildSessionStartedPayload,
  buildTaskAbandonedPayload,
  buildTaskAssignedPayload,
  buildTaskCancelledPayload,
  buildTaskCompletedPayload,
  buildTaskCompletionRequestedPayload,
  buildTaskCreatedPayload,
  buildTaskDeniedPayload,
  buildTaskFailedPayload,
  buildTaskUpdatedPayload,
  buildToolCompletedPayload,
  buildToolFailedPayload,
  buildToolPayload,
  buildToolRequestedPayload,
  buildToolStartedPayload,
  buildTurnFinishedPayload,
  buildTurnQuiescentPayload,
  buildWorkspaceDiscoveredPayload,
  PayloadBuilderError,
} from './payload.js';
export type {
  CanonicalAgentFinishedPayload,
  CanonicalAgentSpawnedPayload,
  CanonicalAgentStateChangedPayload,
  CanonicalPermissionPayload,
  CanonicalPermissionRequestedPayload,
  CanonicalPermissionResolvedPayload,
  CanonicalSessionEndedPayload,
  CanonicalSessionStartedPayload,
  CanonicalTaskAbandonedPayload,
  CanonicalTaskAssignedPayload,
  CanonicalTaskCancelledPayload,
  CanonicalTaskCompletedPayload,
  CanonicalTaskCompletionRequestedPayload,
  CanonicalTaskCreatedPayload,
  CanonicalTaskDeniedPayload,
  CanonicalTaskFailedPayload,
  CanonicalTaskUpdatedPayload,
  CanonicalToolCompletedPayload,
  CanonicalToolFailedPayload,
  CanonicalToolPayload,
  CanonicalToolRequestedPayload,
  CanonicalToolStartedPayload,
  CanonicalTurnFinishedPayload,
  CanonicalTurnQuiescentPayload,
  CanonicalWorkspaceDiscoveredPayload,
  PayloadBuilderErrorCode,
  PermissionPayloadPhase,
  ToolPayloadPhase,
} from './payload.js';

export {
  createOpaqueIdDeriver,
  deriveOpaqueId,
  isOpaqueId,
  opaqueIdEntityTypes,
  OpaqueIdError,
  OPAQUE_ID_KEY_BYTES,
  OPAQUE_ID_OUTPUT_BYTES,
  MAX_OPAQUE_ID_COMPONENT_CODE_UNITS,
  MAX_OPAQUE_ID_COMPONENTS,
  MAX_OPAQUE_ID_INPUT_BYTES,
} from './identity.js';
export type {
  OpaqueId,
  OpaqueIdDeriver,
  OpaqueIdEntityType,
  OpaqueIdErrorCode,
  OpaqueIdInput,
  OpaqueIdKey,
} from './identity.js';
