export type AdapterBoundary = 'sanitized-ingress' | 'capability-profile';

export {
  adapterBoundaryDiagnosticCodes,
  adapterDiagnosticCodes,
  adapterDiagnosticFields,
  adapterDiagnosticSeverities,
  buildAdapterDiagnostic,
  createAdapterDiagnostic,
  isAdapterBoundaryDiagnosticCode,
  isAdapterDiagnosticCode,
  isProtocolDiagnosticCode,
  MAX_DIAGNOSTIC_COUNT,
  MAX_DIAGNOSTIC_DURATION_MS,
  MAX_DIAGNOSTIC_INPUT_WORK,
  normalizeAdapterDiagnostic,
  protocolDiagnosticFields,
} from './diagnostics.js';
export type {
  AdapterBoundaryDiagnosticCode,
  AdapterDiagnostic,
  AdapterDiagnosticBoundary,
  AdapterDiagnosticCode,
  AdapterDiagnosticField,
  AdapterDiagnosticInput,
  AdapterDiagnosticRecord,
  AdapterDiagnosticSeverity,
  ProtocolDiagnosticField,
} from './diagnostics.js';

export {
  categorizeBuiltinTool,
  categorizeBuiltInTool,
  categorizeTool,
  canonicalToolName,
  canonicalToolNameForCategory,
  isMcpToolName,
  MCP_TOOL_CATEGORY,
  TOOL_INPUT_PROPERTY_KEYS,
  toolCategories,
  UNKNOWN_TOOL_CATEGORY,
} from './tool-category.js';
export type { CanonicalToolName } from './tool-category.js';

export {
  buildAgentFinishedPayload,
  buildAgentSpawnedPayload,
  buildAgentStateChangedPayload,
  buildPermissionPayload,
  buildPermissionRequestedPayload,
  buildPermissionResolvedPayload,
  buildSessionEndedPayload,
  buildSessionStartedPayload,
  buildTaskAbandonedPayload,
  buildTaskAssignedPayload,
  buildTaskCancelledPayload,
  buildTaskCompletedPayload,
  buildTaskCompletionRequestedPayload,
  buildTaskCreatedPayload,
  buildTaskDeniedPayload,
  buildTaskFailedPayload,
  buildTaskUpdatedPayload,
  buildToolCompletedPayload,
  buildToolFailedPayload,
  buildToolPayload,
  buildToolRequestedPayload,
  buildToolStartedPayload,
  buildTurnFinishedPayload,
  buildTurnQuiescentPayload,
  buildWorkspaceDiscoveredPayload,
  PayloadBuilderError,
} from './payload.js';
export type {
  CanonicalAgentFinishedPayload,
  CanonicalAgentSpawnedPayload,
  CanonicalAgentStateChangedPayload,
  CanonicalPermissionPayload,
  CanonicalPermissionRequestedPayload,
  CanonicalPermissionResolvedPayload,
  CanonicalSessionEndedPayload,
  CanonicalSessionStartedPayload,
  CanonicalTaskAbandonedPayload,
  CanonicalTaskAssignedPayload,
  CanonicalTaskCancelledPayload,
  CanonicalTaskCompletedPayload,
  CanonicalTaskCompletionRequestedPayload,
  CanonicalTaskCreatedPayload,
  CanonicalTaskDeniedPayload,
  CanonicalTaskFailedPayload,
  CanonicalTaskUpdatedPayload,
  CanonicalToolCompletedPayload,
  CanonicalToolFailedPayload,
  CanonicalToolPayload,
  CanonicalToolRequestedPayload,
  CanonicalToolStartedPayload,
  CanonicalTurnFinishedPayload,
  CanonicalTurnQuiescentPayload,
  CanonicalWorkspaceDiscoveredPayload,
  PayloadBuilderErrorCode,
  PermissionPayloadPhase,
  ToolPayloadPhase,
} from './payload.js';

export {
  createOpaqueIdDeriver,
  deriveOpaqueId,
  isOpaqueId,
  opaqueIdEntityTypes,
  OpaqueIdError,
  OPAQUE_ID_KEY_BYTES,
  OPAQUE_ID_OUTPUT_BYTES,
  MAX_OPAQUE_ID_COMPONENT_CODE_UNITS,
  MAX_OPAQUE_ID_COMPONENTS,
  MAX_OPAQUE_ID_INPUT_BYTES,
} from './identity.js';
export { scanPrivacyCanaries } from './privacy-canary.js';
export type { CanaryScanResult } from './privacy-canary.js';

export {
  buildSanitizedIngressRecord,
  deriveStableEventId,
  deriveStableRetryEventId,
  MAX_INGRESS_RECORD_BYTES,
  MAX_INGRESS_RECORD_DEPTH,
  prepareSanitizedIngressRecord,
  isAcceptedIngressPreparation,
  sanitizeIngressRecord,
  StableRetryEventIdError,
} from './ingress.js';
export {
  IPC_DEADLINE_MS,
  MAX_SPOOL_BYTES,
  MAX_SPOOL_RECORDS,
  MAX_SPOOL_RECORD_BYTES,
  createSanitizedIngressHandoff,
  recoverSpool,
  sendCanonicalIpc,
  spoolCanonical,
  validateInstallationEndpoint,
  deriveInstallationEndpoint,
  deriveLocalEndpoint,
} from './transport.js';
export type {
  IpcResult,
  LocalEndpoint,
  SanitizedIngressHandoff,
  SpoolResult,
} from './transport.js';
export type {
  AcceptedIngressPreparation,
  CanonicalIngressJson,
  IngressHandoffResult,
  IngressPreparationResult,
  IngressRecordOptions,
  IngressTransportWriter,
  SanitizedIngressRecord,
  StableRetryEventIdErrorCode,
} from './ingress.js';
export {
  buildDirectEvent,
  deliverDirectEvent,
  directNativeIdentity,
  directNativeTimestamp,
  recordDirectDiagnostic,
  readDirectHookInput,
  DIRECT_HOOK_DATA_ENV,
  DIRECT_HOOK_SALT_FILE,
  DIRECT_HOOK_EPOCH_FILE,
  DIRECT_HOOK_RUNTIME_FILE,
  DIRECT_HOOK_RUNTIME_COMPAT_FILE,
  DIRECT_HOOK_SPOOL_DIRECTORY,
  DIRECT_HOOK_DIAGNOSTICS_DIRECTORY,
  DIRECT_HOOK_DIAGNOSTIC_LIMIT,
} from './direct-hook.js';
export type { DirectEventDescriptor } from './direct-hook.js';
export type {
  OpaqueId,
  OpaqueIdDeriver,
  OpaqueIdEntityType,
  OpaqueIdErrorCode,
  OpaqueIdInput,
  OpaqueIdKey,
} from './identity.js';
